spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://223.130.152.102/test_triplay
    username: user
    password: 1234
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "https://localhost:5173/callback"
            authorization-grant-type: authorization_code
            scope: profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
      resource-server:
        jwt:
          secret: ${JWT_SECRET}
          expiration: 86400
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${KEY_PASSWORD}
    key-store-type: PKCS12
    key-alias: triplay
app:
  firebase-configuration-file: ./triplayServiceAccountKey.json
  firebase-bucket: ${FIREBASE_STORAGE_BUCKET}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}